USE master
GO

CREATE DATABASE KIEUANHSHOP

GO 
USE KieuAnhShop
GO 

CREATE TABLE SANPHAM(
	IDSP INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TENSP NVARCHAR(50) NOT NULL,
	MOTA NTEXT,
	GIA DECIMAL(10,2) NOT NULL,
	SOLUONGTRONGKHO INT NOT NULL
)

CREATE TABLE CHITETSP(
	IDCTSP INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IDSP INT NOT NULL,
	KICHTHUOC NVARCHAR(20),
	MAUSAC NVARCHAR(20),
	FOREIGN KEY (IDSP) REFERENCES dbo.SANPHAM(IDSP)
)

CREATE TABLE HOADON(
	IDHD INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	IDKHACHHANG INT NOT NULL,
	NGAYTAO DATE,
	TONGTIEN DECIMAL(12,2) NOT NULL,
	TRANGTHAI BIT,
)

CREATE TABLE CHITIETHOADON (
    IDCTHD INT IDENTITY(1,1) PRIMARY KEY,
    IDHD INT,
    SLSP INT NOT NULL,
    TONGTIENSP DECIMAL(12, 2) NOT NULL,
    FOREIGN KEY (IDHD) REFERENCES dbo.HOADON(IDHD)
)

CREATE TABLE CHITIETSPTRONGHOADON (
    IDSPCTTHD INT PRIMARY KEY,
    IDHDCT INT,
    IDSP INT,
    SOLUONG INT NOT NULL,
    GIA DECIMAL(10, 2) NOT NULL,
    TONGTIEN DECIMAL(12, 2) NOT NULL,
    FOREIGN KEY (IDHDCT) REFERENCES dbo.CHITETSP(IDCTSP),
    FOREIGN KEY (IDSP) REFERENCES dbo.SANPHAM(IDSP)
);

