USE KieuAnhShop
GO

SELECT SANPHAM.IDSP, TENSP, KICHTHUOC, MAUSAC, GIA, SOLUONGTRONGKHO, MOTA FROM dbo.SANPHAM
	JOIN dbo.CHITETSP ON CHITETSP.IDSP = SANPHAM.IDSP
SELECT * FROM dbo.SANPHAM

SELECT * FROM dbo.HOADON
SELECT * FROM dbo.HOADON WHERE TRANGTHAI = 1

SELECT * FROM dbo.CHITIETHOADON
SELECT * FROM dbo.CHITIETHOADON WHERE IDHD = 6

SELECT * FROM dbo.CHITIETSPTRONGHOADON

GO 
CREATE VIEW v_GioHang
AS
SELECT ctsp.IDSPCTTHD, cthd.IDCTHD, cthd.IDHD,ctsp.IDSP, TENSP,ctsp.SOLUONG, 
	ctsp.GIA AS 'GiaSanPham', ctsp.TONGTIEN,cthd.SLSP AS 'SoLuongSPTrongHD', 
	HOADON.TONGTIEN AS 'So Tien Can Thanh Toan' FROM dbo.CHITIETSPTRONGHOADON ctsp
		JOIN dbo.CHITIETHOADON cthd ON ctsp.IDHDCT = cthd.IDCTHD
		JOIN dbo.SANPHAM ON SANPHAM.IDSP = ctsp.IDSP
		JOIN dbo.HOADON ON HOADON.IDHD = cthd.IDHD
GO 

SELECT * FROM dbo.v_GioHang




	
    


