USE KieuAnhShop
GO

SELECT SANPHAM.IDSP, TENSP, KICHTHUOC, MAUSAC, GIA, SOLUONGTRONGKHO, MOTA FROM dbo.SANPHAM
	JOIN dbo.CHITETSP ON CHITETSP.IDSP = SANPHAM.IDSP
SELECT * FROM dbo.SANPHAM

SELECT * FROM dbo.HOADON 
SELECT * FROM dbo.HOADON WHERE TRANGTHAI = 1

SELECT * FROM dbo.CHITIETHOADON
SELECT * FROM dbo.CHITIETSPTRONGHOADON

